### ISSUE TITLE
Slider and button alterations

### ISSUE THREAD

**Issue by TimothyMartinez** [aaronholla/design-mockup#1]
Going to try to change the buttons at the top of your page and get double sliders.

**Comment by aaronholla** [comment]
Couldn't sleep took a nap when I got home lol. Something I just noticed that might be a quicker fix. The prices on the stops aren't right aligned.

![flights](https://user-images.githubusercontent.com/2300298/60318200-1f15f480-9940-11e9-81fb-57c37d2f9b37.png)
